name: Pull request - CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./SocialNetworkAPI.sln

      - name: Build solution
        run: dotnet build ./SocialNetworkAPI.sln --no-restore

      - name: Run unit tests
        run: dotnet test --no-build
