name: Push - CI

on:
  push:
    branches:
      - develop
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build solution
        run: dotnet build ..sln

      - name: Run tests with coverage
        working-directory: ./SocialNetworkTests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:./TestResults/**/coverage.cobertura.xml \
          -targetdir:./TestResults/CoverageReport \
          -reporttypes:Html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./TestResults/CoverageReport

      check_branches_convention:
        name: Conventional Branches Name
        runs-on: ubuntu-latest

        steps:
          - uses: deepakputhraya/action-branch-name@master
            with:
              regex: '^(feature|hotfix)/(ID-[0-9]+/[a-zA-Z0-9-]+|no-ref/[a-zA-Z0-9-]+)$'
              allowed_prefixes: 'feature,hotfix'
              ignore: main,develop
              min_length: 4
              max_length: 50

      check_commit_messages:
        name: Conventional Commits Message
        runs-on: ubuntu-latest

        steps:
          - uses: gsactions/commit-message-checker@v2
            with:
              pattern: '(?:feat|fix|chore|test|docs|refactor|revert|hotfix)(?:\(\w+\))?:\s[a-z]{1,2}.+'
              error: 'The commit message must have the following structure: <type>(?): <description>'
              excludeDescription: 'true'
              excludeTitle: 'true'
              checkAllCommitMessages: 'true'
              accessToken: ${{ secrets.GITHUB_TOKEN }}
              