name: Push - CI

on:
  push:
    branches:
      - develop
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        working-directory: ./SocialNetworkApi
        run: dotnet restore 

      - name: Build solution
        run: dotnet build ./SocialNetworkAPI.sln --no-restore

      # Run tests and collect coverage
      - name: Run tests with coverage
        working-directory: ./SocialNetworkTests
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Generate the coverage report using ReportGenerator
      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:./TestResults/**/coverage.cobertura.xml \
          -targetdir:./TestResults/CoverageReport \
          -reporttypes:Html

      # Upload the coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./TestResults/CoverageReport
